spring:
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      jakarta:
        persistence:
          validation:
            mode: none

#spring:
#  profiles:    active:
#                 - dev
#  h2:
#    console:
#      enabled: true
#      path: /h2-console  jpa:    properties:      javax:
#                                 persistence:
#                                   validation:
#                                     mode: none  data:    web:      pageable:        default-page-size: 10
#                                 max-page-size: 100
#---
#spring:
#  profiles: prod
#  datasource:    url: jdbc:h2:./chatitc-prod
#                   username: sa
#  jpa:    hibernate:      ddl-auto: update
#  h2:
#    console:      enabled: false
#chatitc:
#  upload-path: uploads-prod
#---
#spring:
#  profiles: dev
#  datasource:    url: jdbc:h2:mem:chatitc-dev
#chatitc:
#  upload-path: uploads-dev
#---
#spring:
#  profiles: test
#chatitc:
#  upload-path: uploads-test
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
##    database-platform: org.hibernate.dialect.H2Dialect
#    spring:
#      datasource:
#        url: jdbc:h2:file:/data/demo